#pragma config(Motor,  motorB,          LEFT,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          RIGHT,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard

const float speed = 40.0, angleBeta = (2*PI)*(180/PI), trackWidth = 120.0, diameter = 58.0, distanceS = (trackWidth * .5) * angleBeta, halfDistance = diameter/2;
float angleU = 0,X_r, angularVelo, wR, wL;



task turnRightMotor(){
	resetMotorEncoder(RIGHT);
	angleU = (distanceS *(2/diameter));

	setMotorSyncEncoder(RIGHT,LEFT,-100,angleU,speed);
	wR = (getMotorRPM(RIGHT)) * (PI/180);
	wL = (getMotorRPM(LEFT)) * (PI/180);
	X_r =  halfDistance * (wR + wL);
	angularVelo = (diameter/trackWidth) * (wR - wL);

	displayTextLine(1,"%s: %i","currentAngle",angleU);
	displayTextLine(2,"%s: %i","desiredAngle",angleBeta);
	displayTextLine(3,"%s: %i","X_r ",X_r);
	displayTextLine(4,"%s: %f","Angular Velocity", angularVelo);

}// end of turnRightMotorTask



task main()
{
			startTask(turnRightMotor);
			sleep(5000);

}// end of main()
